AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Hosting:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cloudreach-flappy-bird
      WebsiteConfiguration:
        ErrorDocument: 404.html
        IndexDocument: index.html

  S3HostingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Hosting
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub ${S3Hosting.Arn}/*
